### ISSUE TITLE
Db 사용하여 값 넣고 빼기

### ISSUE THREAD

**Issue by aad3365** [Team2400/Argus#10]
Db 를 이용하여 system usage 를 기록하고 값을 불러올 수 있도록 함수를 작성해주세요.

값을 기록할 때 기록할 때 시점인 timestamp 도 함께 기록해 주세요 언제 기록되었는지 알 수 있게 하기 위함입니다.

값을 가져올 때 limit 를 줄 수 있는지 알아봐주세요.

저장 되는 데이터가 많을 것 이기 때문에 제한을 둘 수 있어야합니다.

값을 넣는 함수 따로, 불러오는 함수 따로 각각 작성 바랍니다.

**Comment by howl201** [comment]
값을 기록하고 불러오는것 작성하였습니다 자세한 사항은 주석으로 달았으니 확인 부탁드립니다
