### ISSUE TITLE
dashboard 메인 로직 구현하기

### ISSUE THREAD

**Issue by aad3365** [Team2400/Argus#18]
timer 를 이용하여 5분 간격 을 두고 다음 작업을 처리하게 해주세요 - (간격은 어떤 변수로 만들고 5분으로 일단 하드코딩 해주세요 추후 간격도 수정 가능하게 해야 할 수 있으므로 입니다).

작업요약
1. Usage 클래스를 이용해서 값을 뽑는다.
2. db 에 값을 insert 한다.
3. db 에서 10개의 값을 pull 한다.
4. chartUpdate 함수를 사용하여 chart 를 update 해준다.

3 -> 4 로 넘어가는 과정에서 delegate 를 필요로 할 수도 있겠습니다.

**Comment by howl201** [comment]
![image](https://github.com/Team2400/Argus/assets/104803826/f8c44879-c3c1-420c-8d27-f9aeb5f338c0)
초반 상황
<img width="440" alt="image" src="https://github.com/Team2400/Argus/assets/104803826/9c809917-c6e3-4be5-89b3-088fe4461dce">
최대치를 x축의 60에 맞췄습니다 일단 5초마다 한번씩 갱신하여 출력중입니다.
최대치를 맞추지 않으면
![image](https://github.com/Team2400/Argus/assets/104803826/fc157a1e-230e-4a26-a1b3-8d1d65f1f9c6)
이와 같이 그래프의 x축이 잘리는 현상이 발생합니다.

**Comment by aad3365** [comment]
초반상황은 문제 없어보입니다 값이 조금 덜있어도 그만큼만 보여주는것은 괜찮은 방향같습니다.
![image](https://github.com/Team2400/Argus/assets/17927890/0c34879a-805a-47f8-ba01-be1654e3c68a)
실제로 db 를 열어보니 우려했던 오차는 그렇게 크지 않았습니다.
5초 간격으로 설정하고 돌려본 것인데, timestamp 또한 5초로 일정하게 찍히고 있습니다.
