### ISSUE TITLE
dashboard 에 이미 오랜시간이 흐른 data 가 최근 data 로 보이는 문제

### ISSUE THREAD

**Issue by aad3365** [Team2400/Argus#21]
현재 dashboard 의 문제점중 하나인 item 별 시간이, 또는 시간 간격이? 올바르지 않습니다.

예를 들어

item1 -> 00:00:00 (시 분 초)
item2 -> 00:00:05
item3 -> 00:00:10
item4 -> 00:00:15

까지 db에 item 을 저장했고, 10분 후에 다시 켰다고 했을 때 다음과 같은 현상이 발생합니다.

item5 -> 00:10:02
item6 -> 00:10:07

하지만 현재 코드에서는 13개의 값을 가져오기 때문에 간격이 있든 없든 그냥 가져와서 dashboard 에 순차적으로 보여줍니다.

따라서 다음 두 가지를 해결해야합니다.

1. 시간간격이 존재하는 경우 해당 간격만큼 0으로 "보여줄 list" 에 담아야 한다.
2. 시작시점이 2초, 1초 등 random 하므로 0초 5초 등으로 고정할 필요가 있다.

2번 사항도 중요한 이유는 이것이 맞지 않으면 이전 item 과 최대 9초 차이가 발생할 수 있기 때문입니다.

**Comment by howl201** [comment]
<img width="717" alt="image" src="https://github.com/Team2400/Argus/assets/104803826/27145edf-28fb-4243-bfe5-7efb4fc56bd6">
오랫동안 껐다가 켰을 시
<img width="717" alt="image" src="https://github.com/Team2400/Argus/assets/104803826/8efdc4f9-3600-4184-aebe-196f478e783e">
잠시 껐다가 켰을 시

위와 같이 측정이 안된 시간대는 0으로 처리하여 측정하지 않았을 때의 값을 처리했습니다. 값의 간격은 5초로 하니 값을 기록 시 지연 현상이 발생했을 시 중간에 값이 비는 현상이 관측되어 간격을 6초로 하면서 별다른 반올림 처리는 하지 않았습니다. 이는 좀 더 보면서 다른 분들의 의견을 받아서 추후에 처리하는 것이 좋아 보입니다

**Comment by howl201** [comment]
CPU 사용량 같은 경우 자체 값이 너무 작다보니 시각적인 큰 효과는 보이지 않습니다.

**Comment by aad3365** [comment]
코멘트 달았습니다 확인부탁드려여
