### ISSUE TITLE
LiteDB Install

### ISSUE THREAD

**Issue by aad3365** [Team2400/Argus#5]
사용할 db 는 LiteDB 라는 nosql Db로 선정하였습니다
사용법이 간단하고 연동도 패키지 인스톨후 using 으로 불러와 사용하는 것이 다이므로 요구사항에 적절하다고 생각하였기 때문입니다

nuget package manager 를 통해 설치해 주세요
공홈 링크: https://www.litedb.org/
nuget: https://www.nuget.org/packages/LiteDB/

**Comment by howl201** [comment]
https://github.com/mbdavid/LiteDB.Studio/releases
LiteDB Viewer입니다.
